### ISSUE TITLE
Cannot read properties of undefined (reading 'length')

### ISSUE THREAD

**Issue by w333m** [victorsouzaleal/twitter-direct-url#11]
Seems like the website used changed _something(?)_ since visiting [https://tweetpik.com/api/tweets](https://tweetpik.com/api/tweets) shows 404 error

```
Error Log:
{
  found: false,
  error: "Cannot read properties of undefined (reading 'length')"
}
```

**Comment by w333m** [comment]
Seems like they changed their whole service as a _twitter media downloading_ platform imo

**Comment by victorsouzaleal** [comment]
Here it still works without any code changes.
![image](https://user-images.githubusercontent.com/4674786/210174991-89919431-2e62-487f-a8f8-3d3295866263.png)

Are you still having problems? What could have happened is that the site suffered an instability as it happened in the last few weeks

**Comment by w333m** [comment]
will try using it locally, might be a problem with my virtual machine

**Comment by w333m** [comment]
![image](https://user-images.githubusercontent.com/43951246/210223932-c2a4acc2-a1f2-4a21-88b5-2f635e4a54ec.png)

Running perfectly normal on my local machine, its an error within my virtual machine environment, my bad mate
