### ISSUE TITLE
Sugestion

### ISSUE THREAD

**Issue by eliabexp** [victorsouzaleal/twitter-direct-url#6]
Hi, I have downloaded your package and I loved it!
I have a little sugestion, and it is to add the @ of the user who posted the video

Thank you!

**Comment by victorsouzaleal** [comment]
I changed the source that provides the data, so now I can put more information like @, description, more.. But if I have to change it again I can't guarantee that I'll be able to have this data, I'll add it in the next update but be aware of this may stop working in future updates..  I only guarantee the direct links.

**Comment by victorsouzaleal** [comment]
added on v1.0.7, thank you :)

**Comment by eliabexp** [comment]
Thank you so much, I just downloaded it and it worked perfectly
This is the best api I ever used to get direct links from twitter :)

**Comment by eliabexp** [comment]
pera, vc é brasileiro? @victorsouzaleal

**Comment by eliabexp** [comment]
mano KKKKKKKKKKKKK agora que eu fui ver, valeu mesmo mano, sua api é nota 1000

**Comment by victorsouzaleal** [comment]
sou kkkkkkkkk, valeu mano 😆
