### ISSUE TITLE
spelling of 'width' is wrong

### ISSUE THREAD

**Issue by abhaybhatt** [victorsouzaleal/twitter-direct-url#8]
![image](https://user-images.githubusercontent.com/53853574/203771400-94cd4cfb-c81e-4cec-bc8d-8f1b6292d336.png)

**Comment by victorsouzaleal** [comment]
Can you send me the link of the video you used as an example?

**Comment by victorsouzaleal** [comment]
Fixed in the lastest version, thanks :)
